url: "zubayrali.in" # NOTICE THE ABSENCE OF A TRAILING SLASH
baseurl: "/" # `social` or `mastodon`, for example (NOTICE THE PREFIXING SLASH)

remote_theme: EthanMcBloxxer/jekyll-theme-mastodon@main
plugins:
  - jekyll-remote-theme
